Frontend #2
rcltech/owl pull request #45
Opened 2019-10-18 15:23 UTC by welvin21

New features : 

<ul>
<li>Timepicker component</li>
<li>Time validation functionality</li>
<li>Enable post request to create booking</li>
</ul>

Changes : 

<ul>
<li>Code refactoring</li>
<li>Some components has been shifted to function-based component instead of class</li>
</ul>

2019-10-18 16:23 UTC, 98sean98 commented
there are more changes from @utkarsh867 that haven't been pushed to `frontend-antd`. we should slow down a little. there are some bugs in a few places too.

2019-10-18 17:07 UTC, 98sean98 reviewed
a few notable issues:
- `this.function = this.function.bind(this)` should not be used
- moment object comparisons for time are not done correctly

recommendation:
- use material-ui's `makeStyles` and `useStyles` to handle css properties
- use React functional components and `useState` hooks, while deprecating `constructor` functions

2019-10-18 17:07 UTC, 98sean98 commented on react-app/src/components/complement/Timepicker.js
> +    if (moment(end).format('HH') <= moment(start).format('HH')) {
comparing time should not be done using simple inequality operators such as `<=`
since we are using moment objects, momentjs actually provides a few methods to correctly compare time
one of them is `moment(a).isAfter(b)`, etc.

2019-10-18 17:07 UTC, 98sean98 commented on react-app/src/functions/postBooking.js
> +  };
`createdAt` field is not needed, the development server handles that

2019-10-18 17:07 UTC, 98sean98 commented on react-app/src/functions/getRooms.js
>        let conditionCheck3 = Number(moment(times[i]).format('HH')) <= 23;
this appears to be comparing time as well

2019-10-18 17:07 UTC, 98sean98 commented on react-app/src/components/complement/Menu.js
> +    this.toggle = this.toggle.bind(this);
should not use any more `this.function = this.function.bind(this)` in the latest versions of React

2019-10-24 12:09 UTC, utkarsh867 reviewed
Prefer to use functional components

2019-10-24 12:09 UTC, utkarsh867 commented on react-app/src/components/complement/Menu.js
> +export default class Menu extends Component {
Preferably change to a functional component

2019-10-24 12:09 UTC, utkarsh867 commented on react-app/src/components/complement/Modals.js
> +export default class Modals extends Component {
Change to functional component

2019-10-26 16:19 UTC, 98sean98 commented on react-app/src/components/main/ChooseDate.js
> +  const [date, setDate] = useState(moment(new Date()));
calling `moment()` itself creates a new moment object according to the current time

2019-11-12 14:12 UTC, 98sean98 commented on react-app/src/components/complement/DatePicker.js
> +    value: moment(new Date()),
`moment()` creates a moment object according to the current datetime

2019-11-12 15:47 UTC, 98sean98 requested changes
still a few changes here and there

2019-11-16 08:24 UTC, 98sean98 approved these changes
a lot to improve. merging to master for now to begin migration to phoenix issue #32

2019-11-16 09:01 UTC, merged